# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false # Changed to false for github

# Setup
title:               Ian Keane
tagline:             '(.com)'
description:         'Welcome to my personal project repository'
url:                 http://keane.site
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ian Keane
  url:               github.com/keanegit
  email:             keanerec@gmail.com

# Custom vars
version:             1.0.0
